name: NanoUtils
version: '${project.version}'
main: me.nanorasmus.nanoutils.Main
api-version: '1.21'
libraries:
  - com.esotericsoftware.kryo:kryo5:5.6.2
commands:
  open_book:
    description: opens a NanoUtils-registered book, only to be used internally.